site_name: Trailer12k Dataset
theme:
  name: material
  favicon: images/favicon.png
  palette:
      primary: red
markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
